//! Everything Domain
//!
//! This file was generated by: `sarzak new "everything"`.
//! It contains the following model:
#![cfg_attr(feature = "doc-images",
cfg_attr(all(),
doc = ::embed_doc_image::embed_image!("everything", "models/everything.png")))]
#![cfg_attr(
    not(feature = "doc-images"),
    doc = "**Doc images not enabled**. Compile with feature `doc-images` and Rust version >= 1.54 \
           to enable."
)]
//!
//! ![Everything Test Model][everything]
use uuid::{uuid, Uuid};

#[macro_use]
pub mod macros;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;

// everything
pub const UUID_NS: Uuid = uuid!("68f2a75c-4397-5ee0-9bae-86b95bd1b866");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_r1() {
        let mut store = ObjectStore::new();

        let rando = RandoObject::new(&mut store);
        let everything = Everything::new(&mut store, &rando, 42, true, 42.0, "uberFoo".to_owned());

        let result = everything_get_one_ro_across_r1!(everything, store);
        assert_eq!(&rando, result);
    }
}
