//! Macros for navigating the "Everything" domain
//!
//! # Generated Code -- edit _with care_.
//!
//! Don't mess with anything between `{"magic":"","kind":"CriticalBlockBegin"}`
//! and `{"magic":"","kind":"CriticalBlockEnd"}`. Otherwise, you should be free
//! to go wild. Happy hacking!
//!
//! Use the following invocation to reproduce:
// {"magic":"","kind":{"IgnoreBlockBegin":{}}}
//! ```shell
//!  /Users/uberfoo/projects/sarzak/nut/target/debug/deps/generate_test_domain-145fdb9ab1f4b4be --nocapture
//! ```
// {"magic":"","kind":"IgnoreBlockEnd"}
// {"magic":"","version":"0.2.0"}
// {"magic":"","version":"0.5.0"}
// {"magic":"","version":"1.0.0"}

/// Macro to traverse [`Everything`][🦀] ➡ [`RandoObject`][🦞], via _R1_
///
/// This macro expects a &[`Everything`][🦀], and returns a &[`RandoObject`][🦞].
///
/// Generated by `nut::domain::generate_macros::generate_binary_macro_referrer_to_referent_imp`
///
/// [🦀]: crate::everything::types::Everything
/// [🦞]: crate::everything::types::RandoObject
// {"magic":"","kind":{"IgnoreBlockBegin":{}}}
///
/// # Example
///
///```
/// # use test_models::everything::RandoObject;
/// # use test_models::everything::Everything;
/// # use test_models::everything_get_one_ro_across_r1;
/// # let mut store = test_models::everything::ObjectStore::new();
///
/// let rando_object_bub = RandoObject::new(&mut store);
/// let troubled_holiday = "living_net".to_owned();
///
/// let everything = Everything::new(&mut store, &rando_object_bub, 42, true, 42.0, troubled_holiday);
///
/// let rando_object_bfx = everything_get_one_ro_across_r1!(everything, store);
/// assert_eq!(&rando_object_bub, rando_object_bfx);
///```
// {"magic":"","kind":"IgnoreBlockEnd"}
#[macro_export]
// {"magic":"","kind":{"CriticalBlockBegin":{"tag":"everything_get_one_ro_across_r1-emit_binary_main"}}}
macro_rules! everything_get_one_ro_across_r1 {
    ($input:expr, $store:expr) => {{
        // {"magic":"","kind":{"CriticalBlockBegin":{"tag":"rando_object-emit_one_unconditional"}}}
        // nut::codegen::template::macros::emit_one_unconditional
        $store.exhume_rando_object(&$input.rando).unwrap()
        // {"magic":"","kind":{"CriticalBlockEnd":{"tag":"rando_object-emit_one_unconditional"}}}
    }};
}
pub use everything_get_one_ro_across_r1;
// {"magic":"","kind":{"CriticalBlockEnd":{"tag":"everything_get_one_ro_across_r1-emit_binary_main"}}}

/// Macro to traverse [`RandoObject`][🦀] ➡ [`Everything`][🦞], via _R1_
///
/// This macro expects a &[`RandoObject`][🦀], and returns a &[`Everything`][🦞].
///
/// Generated by `nut::domain::generate_macros::generate_binary_macro_referent_to_referrer_imp`
///
/// [🦀]: crate::everything::types::RandoObject
/// [🦞]: crate::everything::types::Everything
// {"magic":"","kind":{"IgnoreBlockBegin":{}}}
///
/// # Example
///
///```
/// # use test_models::everything::Everything;
/// # use test_models::everything::RandoObject;
/// # use test_models::everything_get_one_e_across_r1;
/// # let mut store = test_models::everything::ObjectStore::new();
///
/// let rando_object_tie = RandoObject::new(&mut store);
/// let plant_substance = "quarrelsome_wilderness".to_owned();
///
/// let everything = Everything::new(&mut store, &rando_object_tie, 42, true, 42.0, plant_substance);
/// let everything_amk = everything_get_one_e_across_r1!(rando_object_tie, store);
///
/// assert_eq!(&everything, everything_amk);
///```
// {"magic":"","kind":"IgnoreBlockEnd"}
#[macro_export]
// {"magic":"","kind":{"CriticalBlockBegin":{"tag":"everything_get_one_e_across_r1-emit_binary_main"}}}
macro_rules! everything_get_one_e_across_r1 {
    ($input:expr, $store:expr) => {{
//         // {"magic":"","kind":"CriticalBlockBegin"} //⚡️
//         // {"magic":"","kind":{"CriticalBlockBegin":"rando_object-everything-emit_one_unconditional_lookup"}} //⚡️
        // {"magic":"","kind":{"CriticalBlockBegin":{"tag":"rando_object-everything-emit_one_unconditional_lookup"}}}
        // nut::codegen::template::macros::emit_one_unconditional_lookup
        $store
            .iter_everything()
            .find(|z| z.1.rando == $input.id)
            .map(|z| z.1)
            .unwrap()
// ⚡️         // {"magic":"","kind":"CriticalBlockEnd"}
// ⚡️             // {"magic":"","kind":{"CriticalBlockEnd":"rando_object-everything-emit_one_unconditional_lookup"}}
//             // {"magic":"","kind":{"CriticalBlockEnd":{"tag":"rando_object-everything-emit_one_unconditional_lookup"}}} //⚡️
        // {"magic":"","kind":{"CriticalBlockEnd":{"tag":"rando_object-everything-emit_one_unconditional_lookup"}}}
    }};
}
pub use everything_get_one_e_across_r1;
// {"magic":"","kind":{"CriticalBlockEnd":{"tag":"everything_get_one_e_across_r1-emit_binary_main"}}}
